### PR TITLE
ENHANCEMENT ProductWishListForm

### PR DESCRIPTION
**Pull request by muskie9**

### CODE REVIEW

**Review by jsirish — APPROVED** [review]
looks good!

**Comment by muskie9** [comment]
This is in better shape at this point... I'm going to go back through it and add documentation for usage... I need to figure out the form submission tests too.

**Comment by muskie9** [comment]
@jsirish could you give this a once over. It's changed since the initial push.

**Review by jsirish — APPROVED** [review]
sanity check looks good

**Comment by muskie9** [comment]
thnx

**Pull request merged**
